### ISSUE TITLE
Event from grid to form is not working.

### ISSUE THREAD

**Issue by caalador** [vaadin/addressbook-portlet#12]
Running addressbook on 1.0.0.alpha5 for some reason the event fired by grid doesn't make the from portlet get an event.

On the client it would seem that both portlets have registered to the hub and the event from the grid seems to be handled correctly by the hub.:

```
Received xhr message: for(;;);[{"syncId":5,"clientId":5,"execute":[[5,null,[0,9],"return (function() { this.$server['}p']($0, true, $1)}).apply($2)"],[6,null,[0,9],"return (function() { this.$server['}p']($0, true, $1)}).apply($2)"],[[0,12],"return (function() { window.Vaadin.Flow.Portlets.fireEvent('Pluto_address_book_grid_ContactList_510736053_2_', 'contact-selected', {contactId: ['7']})}).apply($0)"]],"timings":[7865,2]}]
VM1014 client-2968C9E98973969FFAE746FDEDC2EE09.cache.js:990 Handling message from server
VM1014 client-2968C9E98973969FFAE746FDEDC2EE09.cache.js:937 Handling dependencies
VM1014 client-2968C9E98973969FFAE746FDEDC2EE09.cache.js:198 handleUIDLMessage: 0 ms
VM1014 client-2968C9E98973969FFAE746FDEDC2EE09.cache.js:198  Processing time was 1ms
portletHub.js:2792 Executing action for portlet: Pluto_address_book_form_ContactForm_510736053_1_
portletHub.js:2833 form element null
portletHub.js:786 impl: executing action. parms=[object Object], element=null
portletHub.js:797 ajax action URL: /pluto/portal/About Apache Pluto/__pdaddress-book-grid.ContactList!510736053%7C2;0/__pdaddress-book-form.ContactForm!510736053%7C1;1/__aa1/__av1;vaadin.ev:contact-selected/__av1;vaadin.uid:0/__av1;vaadin.wn:contextpathservletpath-279733526-0.39708119268467224/__av1;contactId:7/__av1;_csrf:81d1c152-6d4d-408d-a74b-0a1cfb2836f8
portletHub.js:847 ajax action: POST using URL with parameters
portletHub.js:648 Decoding string: >>{"portlets" : {
   "Pluto_address_book_grid_ContactList_510736053_2_" : {
      "state" : {
         "parameters" : {
         }, 
         "portletMode" : "view", 
         "windowState" : "normal"
      },
      "pubParms" : {},
      "allowedPM" : ["view"],
      "allowedWS" : ["normal", "maximized", "minimized"],
      "renderData" : {
         "content" : null,
         "mimeType" : "text/plain"
      },
      "urlpid" : "address-book-grid.ContactList!510736053|2"
   },
   "Pluto_address_book_form_ContactForm_510736053_1_" : {
      "state" : {
         "parameters" : {
         }, 
         "portletMode" : "view", 
         "windowState" : "normal"
      },
      "pubParms" : {},
      "allowedPM" : ["view", "edit"],
      "allowedWS" : ["normal", "maximized", "minimized"],
      "renderData" : {
         "content" : null,
         "mimeType" : "text/plain"
      },
      "urlpid" : "address-book-form.ContactForm!510736053|1"
   }
},
"prpMap" : {
}}<<
portletHub.js:668 decoded state for 2 portlets. # changed = 0
VM1014 client-2968C9E98973969FFAE746FDEDC2EE09.cache.js:198 Sending xhr message to server: {"csrfToken":"b099ef85-8231-4973-8bd5-5b15403125bd","rpc":[{"type":"event","node":1,"event":"ui-poll"}],"syncId":4,"clientId":4}
VM1014 client-2968C9E98973969FFAE746FDEDC2EE09.cache.js:198 
```

**Comment by denis-anisimov** [comment]
This is caused by exception:

```
java.lang.IllegalStateException: Cannot access state in VaadinSession or UI without locking the session.
	at com.vaadin.flow.server.VaadinSession.checkHasLock(VaadinSession.java:524)
	at com.vaadin.flow.server.VaadinSession.checkHasLock(VaadinSession.java:538)
	at com.vaadin.flow.server.VaadinSession.getAttribute(VaadinSession.java:746)
	at com.vaadin.flow.portal.VaadinPortlet.getViewContext(VaadinPortlet.java:502)
	at com.vaadin.flow.portal.VaadinPortlet.processAction(VaadinPortlet.java:355)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.pluto.container.bean.processor.AnnotatedMethod.invoke(AnnotatedMethod.java:187)
	at org.apache.pluto.container.bean.processor.PortletInvoker.invokePortletMethod(PortletInvoker.java:148)
	at org.apache.pluto.container.bean.processor.PortletInvoker.processAction(PortletInvoker.java:406)
	at org.apache.pluto.driver.services.container.FilterChainImpl.doFilter(FilterChainImpl.java:196)
	at org.apache.pluto.driver.services.container.FilterChainImpl.processFilter(FilterChainImpl.java:153)
	at org.apache.pluto.driver.services.container.FilterManagerImpl.processFilter(FilterManagerImpl.java:142)
	at org.apache.pluto.container.driver.PortletServlet3.dispatch(PortletServlet3.java:519)
	at org.apache.pluto.container.driver.PortletServlet3.doPost(PortletServlet3.java:340)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:591)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:527)
	at org.apache.pluto.driver.container.DefaultPortletInvokerService.invoke(DefaultPortletInvokerService.java:248)
	at org.apache.pluto.driver.container.DefaultPortletInvokerService.action(DefaultPortletInvokerService.java:98)
	at org.apache.pluto.container.impl.PortletContainerImpl.doAction(PortletContainerImpl.java:336)
```

**Comment by denis-anisimov** [comment]
PR : https://github.com/vaadin/portlet-support/pull/144
